# Generated by Django 2.0 on 2019-02-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190216_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('center_id',),
            },
        ),
        migrations.AlterField(
            model_name='database',
            name='previous_allotment',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='previous_centers',
            field=models.TextField(default=None, null=True),
        ),
    ]
