# Generated by Django 2.0 on 2019-02-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190216_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='allotted',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
