# Generated by Django 2.0 on 2019-02-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_center_allotted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='allotted',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
