# Generated by Django 2.0 on 2019-02-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190216_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='allotted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
