# Generated by Django 2.0 on 2019-02-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190216_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='imei',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='tab_id',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
