# Generated by Django 2.0 on 2019-02-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190216_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='imei',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
