# Generated by Django 2.0 on 2019-02-16 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190216_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='end_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='start_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
