# Generated by Django 2.0 on 2019-02-16 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190216_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
