# Generated by Django 2.0 on 2019-02-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190216_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='database',
            name='damaged',
            field=models.BooleanField(default=False),
        ),
    ]
