# Generated by Django 2.0 on 2019-02-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190216_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='previous_allotment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
