# Generated by Django 2.0 on 2019-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190216_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='allotted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='database',
            name='allotted_to',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
