# Generated by Django 2.0 on 2019-02-16 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190216_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='allotted_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='received_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
