# Generated by Django 2.0 on 2019-02-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190216_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
