# Generated by Django 2.0 on 2019-02-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190216_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='project',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
