# Generated by Django 2.0 on 2019-02-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_database_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='previous_centers',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
