# Generated by Django 2.0 on 2019-02-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190216_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='Brand',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
