# Generated by Django 2.0 on 2019-02-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_database_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='Brand',
            new_name='brand',
        ),
    ]
