# Generated by Django 2.0 on 2019-02-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190218_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='allotted_time',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='received_time',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
