# Generated by Django 2.0 on 2019-02-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190218_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='end_time',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='start_time',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
