# Generated by Django 2.0 on 2019-02-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_maintenance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='completed',
            new_name='under_maintenance',
        ),
    ]
